baseURL = "https://DcDoc311.github.io/"
languageCode = "en-us"
title = "Below the Line"
theme = "hextra"

[pagination]
	paginate = 10

[params]
  description = "Low-level, Embedded, Linker notes"
  googleAnalytics = "G-TQKK5MMCJW"
 
[params.author]
  name = "LEE"

  
[menu]
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 1

[taxonomies]
  category = "categories"
  tag = "tags"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	  
  [markup.tableOfContents]
    startLevel = 0
    endLevel = 3